/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Main;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FleetDirectory;
import Interface.Airliners.AirlinerChooser;
import Interface.Customer.FlightBookingPage1;
import Interface.TravelAgency.ManageAirliner;
import java.awt.CardLayout;

/**
 *
 * @author admin
 */
public class MainFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainFrame
     */
    private AirlinerDirectory airlinerDictionary;
    private CustomerDirectory customerDirectory;
    
    private FleetDirectory fleetDirectory;
    public MainFrame() {
        initComponents();
        airlinerDictionary = new AirlinerDirectory();
        customerDirectory=new CustomerDirectory();
        fleetDirectory = new FleetDirectory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftpane = new javax.swing.JPanel();
        btnTravelAgency = new javax.swing.JButton();
        btnAirliner = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rightpane = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftpane.setBackground(new java.awt.Color(102, 204, 255));
        leftpane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTravelAgency.setBackground(new java.awt.Color(255, 255, 255));
        btnTravelAgency.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnTravelAgency.setText("Travel Agency");
        btnTravelAgency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelAgencyActionPerformed(evt);
            }
        });
        leftpane.add(btnTravelAgency, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 150, 39));

        btnAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnAirliner.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnAirliner.setText("Airliner");
        btnAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAirlinerActionPerformed(evt);
            }
        });
        leftpane.add(btnAirliner, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 150, 39));

        btnCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnCustomer.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnCustomer.setText("Customer");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });
        leftpane.add(btnCustomer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 150, 39));

        jLabel1.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel1.setText("STUDENT");
        leftpane.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Corbel", 1, 24)); // NOI18N
        jLabel2.setText("UNIVERSE");
        leftpane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, -1, -1));

        jSplitPane1.setLeftComponent(leftpane);

        rightpane.setBackground(new java.awt.Color(102, 204, 255));
        rightpane.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightpane);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1064, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTravelAgencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelAgencyActionPerformed
        // TODO add your handling code here:
        
        
        ManageAirliner ma = new ManageAirliner(rightpane,airlinerDictionary,customerDirectory,fleetDirectory);
        rightpane.add("ManageAirliner",ma);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_btnTravelAgencyActionPerformed

    private void btnAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAirlinerActionPerformed
        // TODO add your handling code here:
        
        AirlinerChooser la = new AirlinerChooser(rightpane,airlinerDictionary, fleetDirectory);
        rightpane.add("LoginAirliner",la);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_btnAirlinerActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        // TODO add your handling code here:
        
        FlightBookingPage1 cs= new FlightBookingPage1(rightpane,airlinerDictionary,customerDirectory);
        rightpane.add("CustomerSpecification",cs);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_btnCustomerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAirliner;
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnTravelAgency;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel leftpane;
    private javax.swing.JPanel rightpane;
    // End of variables declaration//GEN-END:variables
}
