/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliners;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.Fleet;
import Business.FleetDirectory;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class AirlinerChooser extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerChooser
     */
    
    JPanel rightpane;
    AirlinerDirectory airlineDirectory;
    Airliner airliner;
    FleetDirectory fleetDirectory;
    Fleet fleet;
    
    public AirlinerChooser(JPanel rightpane, AirlinerDirectory airlineDirectory, FleetDirectory fleetDirectory) {
        initComponents();
        this.rightpane=rightpane;
        this.airliner=airliner;
        this.airlineDirectory=airlineDirectory;
        this.fleetDirectory=fleetDirectory;
        
        comboAirlinerSelection.removeAllItems();
       for(Airliner a : airlineDirectory.getairlinerDirectory()) {
           comboAirlinerSelection.addItem(a);
       }
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        airlinernamelabel = new javax.swing.JLabel();
        comboAirlinerSelection = new javax.swing.JComboBox();
        gobtn = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));

        airlinernamelabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        airlinernamelabel.setText("Airliner:");

        comboAirlinerSelection.setBackground(new java.awt.Color(102, 204, 255));
        comboAirlinerSelection.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        comboAirlinerSelection.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        comboAirlinerSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboAirlinerSelectionActionPerformed(evt);
            }
        });

        gobtn.setBackground(new java.awt.Color(102, 204, 255));
        gobtn.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        gobtn.setText("GO");
        gobtn.setMaximumSize(new java.awt.Dimension(64, 29));
        gobtn.setMinimumSize(new java.awt.Dimension(34, 29));
        gobtn.setPreferredSize(new java.awt.Dimension(34, 29));
        gobtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gobtnActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(102, 204, 255));
        btnBack.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.setPreferredSize(new java.awt.Dimension(65, 29));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(166, 166, 166)
                        .addComponent(airlinernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboAirlinerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(238, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(airlinernamelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboAirlinerSelection, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93)
                .addComponent(gobtn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(284, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void gobtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gobtnActionPerformed
        // TODO add your handling code hese:
       
        Airliner airliner = (Airliner)comboAirlinerSelection.getSelectedItem();
        FleetChooser fleetchooser = new FleetChooser(rightpane, airlineDirectory, airliner, fleetDirectory);
        rightpane.add("FleetChooser",fleetchooser);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
        
        /*AirlinerTableDetails atd = new AirlinerTableDetails(rightpane, a, airlinerDictionary);
        rightpane.add("AirlinerTableDetails",atd);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);*/
    }//GEN-LAST:event_gobtnActionPerformed

    private void comboAirlinerSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboAirlinerSelectionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboAirlinerSelectionActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightpane.remove(this);
         CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.previous(rightpane);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel airlinernamelabel;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox comboAirlinerSelection;
    private javax.swing.JButton gobtn;
    // End of variables declaration//GEN-END:variables
}
