/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.Airliners;

import Business.Flightdetails;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class ViewFlight extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlight
     */
    
JPanel rightpane;
Flightdetails fd;
    ViewFlight(JPanel rightpane, Flightdetails fd) {
        initComponents();
        this.rightpane=rightpane;
        this.fd=fd;
        
        display();
        //notxt.setText(convertInteger(fd.getflighNumber()));
        //sourcetxt.setText(fd.getSource());
        //desttxt.setText(fd.getDestination());
        //seattxt.setText(convertInteger(fd.getSeats()));
        //datetxt.setText(fd.getDate());
        //pricetxt.setText(convertInteger(fd.getPrice()));
        
        //throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
    
    public void display(){
        notxt.setText(String.valueOf(fd.getflighNumber()));
        sourcetxt.setText(fd.getSource());
        desttxt.setText(fd.getDestination());
        seattxt.setText(String.valueOf(fd.getSeats()));
        datetxt.setText(fd.getDate());
        pricetxt.setText(String.valueOf(fd.getPrice()));
}
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fnolabel = new javax.swing.JLabel();
        sourcelabel = new javax.swing.JLabel();
        destlabel = new javax.swing.JLabel();
        seatlabel = new javax.swing.JLabel();
        datelabel = new javax.swing.JLabel();
        pricelabel = new javax.swing.JLabel();
        pricetxt = new javax.swing.JTextField();
        datetxt = new javax.swing.JTextField();
        seattxt = new javax.swing.JTextField();
        desttxt = new javax.swing.JTextField();
        sourcetxt = new javax.swing.JTextField();
        notxt = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 204, 255));
        setPreferredSize(new java.awt.Dimension(900, 600));

        fnolabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        fnolabel.setText("Flight Number:");

        sourcelabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        sourcelabel.setText("Source:");

        destlabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        destlabel.setText("Destination:");

        seatlabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        seatlabel.setText("Seats:");

        datelabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        datelabel.setText("Date:");

        pricelabel.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        pricelabel.setText("Price:");

        pricetxt.setEditable(false);
        pricetxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        pricetxt.setPreferredSize(new java.awt.Dimension(34, 29));

        datetxt.setEditable(false);
        datetxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        datetxt.setPreferredSize(new java.awt.Dimension(34, 29));

        seattxt.setEditable(false);
        seattxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        seattxt.setPreferredSize(new java.awt.Dimension(34, 29));

        desttxt.setEditable(false);
        desttxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        desttxt.setPreferredSize(new java.awt.Dimension(34, 29));

        sourcetxt.setEditable(false);
        sourcetxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        sourcetxt.setPreferredSize(new java.awt.Dimension(34, 29));

        notxt.setEditable(false);
        notxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        notxt.setPreferredSize(new java.awt.Dimension(34, 29));
        notxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notxtActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Flight Details");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(seatlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(sourcelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(26, 26, 26))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(destlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(53, 53, 53)
                                            .addComponent(datelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fnolabel, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(92, 92, 92)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pricelabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(notxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(sourcetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(desttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(451, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnolabel)
                    .addComponent(notxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourcetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desttxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sourcelabel))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatlabel)
                    .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(datelabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pricetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pricelabel))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2166, 2166, 2166))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        notxt.setEditable(true);
        sourcetxt.setEditable(true);
        desttxt.setEditable(true);
        seattxt.setEditable(true);
        datetxt.setEditable(true);
        pricetxt.setEditable(true);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String no= notxt.getText().trim();
        String src=sourcetxt.getText().trim();
        String dest=desttxt.getText().trim();
        int s= Integer.parseInt(seattxt.getText().trim());
        String d=datetxt.getText().trim();
        int p=Integer.parseInt(pricetxt.getText().trim());
        
        fd.setflighNumber(no);
        fd.setSource(src);
        fd.setDestination(dest);
        fd.setSeats(s);
        fd.setDate(d);
        fd.setPrice(p);
        JOptionPane.showMessageDialog(null, "updated successfully");
        
        notxt.setEditable(false);
        sourcetxt.setEditable(false);
        desttxt.setEditable(false);
        seattxt.setEditable(false);
        datetxt.setEditable(false);
        pricetxt.setEditable(false);
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void backAction() {
        rightpane.remove(this);
        Component[] componentArray = rightpane.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirlinerTableDetails atd = (AirlinerTableDetails) component;
        atd.populate1();
        CardLayout layout = (CardLayout) rightpane.getLayout();
        layout.previous(rightpane);
    }
    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        backAction();
    }//GEN-LAST:event_btnBackActionPerformed

    private void notxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_notxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel datelabel;
    private javax.swing.JTextField datetxt;
    private javax.swing.JLabel destlabel;
    private javax.swing.JTextField desttxt;
    private javax.swing.JLabel fnolabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField notxt;
    private javax.swing.JLabel pricelabel;
    private javax.swing.JTextField pricetxt;
    private javax.swing.JLabel seatlabel;
    private javax.swing.JTextField seattxt;
    private javax.swing.JLabel sourcelabel;
    private javax.swing.JTextField sourcetxt;
    // End of variables declaration//GEN-END:variables
}
