/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.Airliner;
import Business.Fleet;
import Business.FleetDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author viee
 */
public class AddFleet extends javax.swing.JPanel {
    
     private FleetDirectory fleetDirectory;
     private Airliner airliner;
    private JPanel rightpane;

    /**
     * Creates new form AddFleet
     */
    

    public AddFleet(JPanel rightpane, Airliner airliner, FleetDirectory fleetDirectory) {
         initComponents(); 
        this.rightpane=rightpane;
        this.airliner=airliner;
        this.fleetDirectory=fleetDirectory;
        airlineName.setText(airliner.getairlinerName());
       //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modeltxt = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnAddAirliner = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        seattxt = new javax.swing.JTextField();
        airlineName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        jLabel1.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jLabel1.setText("Model:");

        modeltxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N

        btnBack.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnAddAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAirliner.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnAddAirliner.setText("Add Airliner");
        btnAddAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirlinerActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jLabel2.setText("Seats:");

        seattxt.setEditable(false);
        seattxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        seattxt.setText("150");
        seattxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seattxtActionPerformed(evt);
            }
        });

        airlineName.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        airlineName.setEnabled(false);

        jLabel3.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        jLabel3.setText("Airline Name:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(66, 66, 66)
                                .addComponent(jLabel2)
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnAddAirliner, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                    .addComponent(seattxt)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(51, 51, 51)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(airlineName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(449, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(airlineName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modeltxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seattxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(btnAddAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(248, Short.MAX_VALUE))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
       rightpane.remove(this);
        CardLayout layout = (CardLayout) rightpane.getLayout();
        layout.previous(rightpane);
        Component[] components = rightpane.getComponents();
        for(Component c : components){
            if(c instanceof FleetWorkArea){
                FleetWorkArea panel = (FleetWorkArea)c;
                panel.populate();
            }
        }
        
        
        
        
        /* rightpane.remove(this);
        Component[] componentArray = rightpane.getComponents();
        Component component = componentArray[componentArray.length-1];
        AirlinerWorkArea AirlinerWorkAreaJPanel=(AirlinerWorkArea) component;
        AirlinerWorkAreaJPanel.populate();
        CardLayout layout=(CardLayout)rightpane.getLayout();
        layout.previous(rightpane);*/
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnAddAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirlinerActionPerformed
       Fleet fleet = fleetDirectory.addFleet();
       fleet.setairPlaneName(airliner.getairlinerName());
        fleet.setModelNumber((modeltxt.getText())); 
        fleet.setSeats(150);
        JOptionPane.showMessageDialog(null, "Fleet Information Captured Successfully");
        rightpane.remove(this);
        CardLayout layout = (CardLayout) rightpane.getLayout();
        layout.previous(rightpane);
        Component[] components = rightpane.getComponents();
        for(Component c : components){
            if(c instanceof FleetWorkArea){
                FleetWorkArea panel = (FleetWorkArea)c;
                panel.populate();
            }
        }
//        modeltxt.setText("");
//        seattxt.setText("");
// TODO add your handling code here:
        
    }//GEN-LAST:event_btnAddAirlinerActionPerformed

    private void seattxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seattxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seattxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlineName;
    private javax.swing.JButton btnAddAirliner;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modeltxt;
    private javax.swing.JTextField seattxt;
    // End of variables declaration//GEN-END:variables
}
