/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.Airliner;
import Business.AirlinerDirectory;
import Business.FleetDirectory;
import Business.Flightdetails;
import Interface.Airliners.ViewFlight;
import java.awt.CardLayout;
import java.awt.Component;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author admin
 */
public class AirlinerWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AirlinerWorkArea
     */
    private JPanel rightpane;
    private AirlinerDirectory airlinerDirectory;
    private FleetDirectory fleetDirectory;
    
    public AirlinerWorkArea(JPanel rightpane, AirlinerDirectory ad, FleetDirectory fleetDirectory) {
           initComponents();
            this.rightpane=rightpane;
         this.airlinerDirectory=ad;
         this.fleetDirectory=fleetDirectory;
         populate();
         
         AirlinerTable.getTableHeader().setFont(new Font("SansSerif",Font.BOLD,34));
         //AirlinerTable.setRowHeight(1, 30);
      
    }
    public void populate(){
        int rowCount = AirlinerTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)AirlinerTable.getModel();
        dtm.setRowCount(0);
        //for(int i = rowCount-1;i>=0;i--){
        //dtm.removeRow(i);
      //  }
        for (Airliner a : airlinerDirectory.getairlinerDirectory()){
            Object[] row = new Object[1];
            row[0] = a;
            dtm.addRow(row);
        }
        
        /*DefaultTableModel dtm = (DefaultTableModel)AirlinerTable.getModel();
        dtm.setRowCount(0);
        
        for(Airliner a : airlinerDirectory.getairlinerDirectory()){
            Object[] row = new Object[dtm.getColumnCount()];
            row[0]=a.getairlinerName();
            
            dtm.addRow(row);
        }*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        AirlinerTable = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDeleteAirline = new javax.swing.JButton();
        btnAddAirliner = new javax.swing.JButton();
        btnViewAirliner = new javax.swing.JButton();
        btnFleetAdd = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));
        setMaximumSize(new java.awt.Dimension(900, 600));
        setMinimumSize(new java.awt.Dimension(900, 600));
        setPreferredSize(new java.awt.Dimension(900, 600));

        AirlinerTable.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        AirlinerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Airliner Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(AirlinerTable);
        if (AirlinerTable.getColumnModel().getColumnCount() > 0) {
            AirlinerTable.getColumnModel().getColumn(0).setResizable(false);
        }

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnDeleteAirline.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteAirline.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnDeleteAirline.setText("Delete");
        btnDeleteAirline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteAirlineActionPerformed(evt);
            }
        });

        btnAddAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnAddAirliner.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnAddAirliner.setText("Add an airliner");
        btnAddAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAirlinerActionPerformed(evt);
            }
        });

        btnViewAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnViewAirliner.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnViewAirliner.setText("View");
        btnViewAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAirlinerActionPerformed(evt);
            }
        });

        btnFleetAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnFleetAdd.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnFleetAdd.setText("Add Fleet");
        btnFleetAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFleetAddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnAddAirliner)
                        .addGap(44, 44, 44)
                        .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(btnDeleteAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(btnFleetAdd))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 848, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteAirline, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFleetAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAirlinerActionPerformed
        // TODO add your handling code here:
        AddAirliner aa = new AddAirliner(rightpane, airlinerDirectory);
       
        rightpane.add("AddAirliner", aa);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_btnAddAirlinerActionPerformed

    private void btnDeleteAirlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteAirlineActionPerformed
        // TODO add your handling code here:
        int selectedRow = AirlinerTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Airliner prod = (Airliner)AirlinerTable.getValueAt(selectedRow, 0);
                airlinerDirectory.removeAirliner(prod);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
       
    }//GEN-LAST:event_btnDeleteAirlineActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightpane.remove(this);
        CardLayout layout=(CardLayout)rightpane.getLayout();
        layout.previous(rightpane);
         
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAirlinerActionPerformed
        // TODO add your handling code here:
        int selectRow= AirlinerTable.getSelectedRow();
        if(selectRow<0)
        {
        JOptionPane.showMessageDialog(null,"Please select a row");
        }
        else{
        Airliner a = (Airliner) AirlinerTable.getValueAt(selectRow,0);
        viewairlinerdetails vad = new viewairlinerdetails(this.rightpane,a);
        rightpane.add("viewairlinerdetails",vad);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
        }
    }//GEN-LAST:event_btnViewAirlinerActionPerformed

    private void btnFleetAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFleetAddActionPerformed
        
        int selectRow= AirlinerTable.getSelectedRow();
        if(selectRow<0)
        {
        JOptionPane.showMessageDialog(null,"Please select an Airliner from the Table!");
        }
        else
        {
        
         Airliner a = (Airliner) AirlinerTable.getValueAt(selectRow,0);
        FleetWorkArea fleetWork = new FleetWorkArea(rightpane, a, fleetDirectory);
        rightpane.add("FleetWorkAre",fleetWork);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);     
        }// TODO add your handling code here:
    }//GEN-LAST:event_btnFleetAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable AirlinerTable;
    private javax.swing.JButton btnAddAirliner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteAirline;
    private javax.swing.JButton btnFleetAdd;
    private javax.swing.JButton btnViewAirliner;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
