/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.Airliner;
import Business.Fleet;
import Business.FleetDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author viee
 */
public class FleetWorkArea extends javax.swing.JPanel {
 
    private JPanel rightpane;
    private FleetDirectory fleetDirectory;
    private Airliner airliner;
    /**
     * Creates new form FleetWorkArea
     */
    

    FleetWorkArea(JPanel rightpane, Airliner airliner, FleetDirectory fleetDirectory) {
        initComponents();
        this.rightpane=rightpane;
        this.fleetDirectory=fleetDirectory;
        this.airliner=airliner;
        airlinertxt.setText(airliner.getairlinerName());
        
        
        
        populate();
  

//To change body of generated methods, choose Tools | Templates.
    }

    
    public void populate(){
        DefaultTableModel dtm = (DefaultTableModel)FleetTable.getModel();
        dtm.setRowCount(0);
        
        for(Fleet a : fleetDirectory.getFleetDirectory()){
            if(airliner.getairlinerName().equalsIgnoreCase(a.getairPlaneName()))
            {
            Object[] row = new Object[dtm.getColumnCount()];
            
            row[0]=a;
            row[1]=a.getSeats();
            dtm.addRow(row);
            }
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FleetTable = new javax.swing.JTable();
        btnDeleteFLeet = new javax.swing.JButton();
        btnAddFleet = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        airlinertxt = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(102, 204, 255));

        FleetTable.setFont(new java.awt.Font("Corbel Light", 0, 14)); // NOI18N
        FleetTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Model", "Seats"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(FleetTable);

        btnDeleteFLeet.setBackground(new java.awt.Color(255, 255, 255));
        btnDeleteFLeet.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnDeleteFLeet.setText("Delete");
        btnDeleteFLeet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFLeetActionPerformed(evt);
            }
        });

        btnAddFleet.setBackground(new java.awt.Color(255, 255, 255));
        btnAddFleet.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnAddFleet.setText("Add a fleet");
        btnAddFleet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddFleetActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        airlinertxt.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        airlinertxt.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(169, 169, 169)
                                .addComponent(btnAddFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(225, 225, 225)
                                .addComponent(btnDeleteFLeet, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(airlinertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(airlinertxt, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteFLeet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddFleet, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(136, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddFleetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddFleetActionPerformed
        AddFleet addfleet = new AddFleet(rightpane, airliner, fleetDirectory);
        rightpane.add("FleetWorkArea",addfleet);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);                // TODO add your handling code here:

    }//GEN-LAST:event_btnAddFleetActionPerformed

    private void btnDeleteFLeetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFLeetActionPerformed
        int selectedRow = FleetTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Fleet fleet = (Fleet)FleetTable.getValueAt(selectedRow, 0);
                fleetDirectory.deleteFleet(fleet);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }        // TODO add your handling code here:

    }//GEN-LAST:event_btnDeleteFLeetActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        rightpane.remove(this);
        CardLayout layout=(CardLayout)rightpane.getLayout();
        layout.previous(rightpane);        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FleetTable;
    private javax.swing.JTextField airlinertxt;
    private javax.swing.JButton btnAddFleet;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteFLeet;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
