/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.TravelAgency;

import Business.AirlinerDirectory;
import Business.CustomerDirectory;
import Business.FleetDirectory;
import Interface.Customer.FlightBookingPage1;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class ManageAirliner extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirliner
     */
    JPanel rightpane;
    private AirlinerDirectory airlinerDirectory;
    private CustomerDirectory customerDirectory;
    private FleetDirectory fleetDirectory;
    public ManageAirliner(JPanel rightpane, AirlinerDirectory airlinerDirectory,CustomerDirectory customerDirectory, FleetDirectory fleetDirectory) {
         initComponents();
         this.rightpane=rightpane;
         this.airlinerDirectory=airlinerDirectory;
         this.customerDirectory=customerDirectory;
         this.fleetDirectory=fleetDirectory;
         
      //  throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnManageAirliner = new javax.swing.JButton();
        btnViewCustomer = new javax.swing.JButton();

        setBackground(new java.awt.Color(102, 204, 255));

        btnManageAirliner.setBackground(new java.awt.Color(255, 255, 255));
        btnManageAirliner.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnManageAirliner.setText("Manage Airliners ");
        btnManageAirliner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAirlinerActionPerformed(evt);
            }
        });

        btnViewCustomer.setBackground(new java.awt.Color(255, 255, 255));
        btnViewCustomer.setFont(new java.awt.Font("Corbel Light", 1, 18)); // NOI18N
        btnViewCustomer.setText("View Customer");
        btnViewCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnManageAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(328, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnManageAirliner, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(btnViewCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageAirlinerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAirlinerActionPerformed
        // TODO add your handling code here:
        AirlinerWorkArea awa = new AirlinerWorkArea(rightpane, airlinerDirectory,fleetDirectory);
        rightpane.add("AirlinerWorkArea", awa);
        CardLayout layout = (CardLayout)rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_btnManageAirlinerActionPerformed

    private void btnViewCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewCustomerActionPerformed
        // TODO add your handling code here:
              customerdetailsJPanel cdp = new customerdetailsJPanel(rightpane,customerDirectory);
        rightpane.add("customerdetailsJPanel",cdp);
        CardLayout layout=(CardLayout) rightpane.getLayout();
        layout.next(rightpane);
    }//GEN-LAST:event_btnViewCustomerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAirliner;
    private javax.swing.JButton btnViewCustomer;
    // End of variables declaration//GEN-END:variables
}
